# {{ansible_managed}}

# Load configurations that have been placed .bashrc
if [ -f ~/.bashrc ]; then source ~/.bashrc; fi

# Custom User config
alias ll="ls -lahG"

# History
export HISTTIMEFORMAT="%b %d %I:%M %p	 "
export HISTCONTROL=ignoreboth	# ignoredups:ignorespace

# GREP - options that grep should use by default
export GREP_OPTIONS="--color=auto -E"

# Console colors
export LSCOLORS=gxfxcxdxbxegedabagacad

# Simplifies the path of all the rails bin files
export PATH="./bin:$PATH"

### Git autocompletion, prompt coloring, and aliases
if [ -f ~/.git-completion.bash ]; then
	source ~/.git-completion.bash
	# The following 3 functions are to customize the git prompt.
	function parse_git_dirty {
		[[ $(git status 2> /dev/null | tail -n1) != "nothing to commit (working directory clean)" ]] && echo ""
	}
	function parse_git_branch {
		git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/[\1$(parse_git_dirty)] /"
	}
	function beautify_git_prompt {
		local ORANGE="\[\e[28;1m\]"
		local ORIGINAL="\[\033[m\]"
    local GREEN="\e[32m"
    local CYAN="\e[36m"
		PS1="$CYAN\u@\h$ORIGINAL $ORANGE\W $GREEN\$(parse_git_branch)$ORIGINAL\$ "	# PS1="$ORANGE\W $GREEN\$(git branch | awk '/\* /') $ORIGINAL\$ "
	}
	beautify_git_prompt
	alias gitlog="git log --graph --oneline --decorate -25"
	alias gitlogs="git log --graph --oneline --decorate"
fi
